# Generated by Django 3.2 on 2021-04-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='empty', max_length=30)),
                ('lname', models.CharField(default='empty', max_length=30)),
            ],
        ),
    ]
