# Generated by Django 3.2 on 2021-04-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='empty', max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='empty', max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='empty', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='empty', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='pphone',
            field=models.CharField(default='empty', max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='wphone',
            field=models.CharField(default='empty', max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='zip',
            field=models.CharField(default='empty', max_length=5),
        ),
    ]
