# Generated by Django 3.2 on 2021-04-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduler', '0002_auto_20210426_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='empty', max_length=30, null=True),
        ),
    ]
