# Generated by Django 3.2 on 2021-04-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduler', '0005_user_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='empty', max_length=30),
        ),
    ]
