# Generated by Django 3.2 on 2021-04-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduler', '0008_auto_20210426_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pphone',
            field=models.CharField(default='empty', max_length=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='wphone',
            field=models.CharField(default='empty', max_length=12),
        ),
    ]
