# Generated by Django 3.2 on 2021-04-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduler', '0010_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='number',
            field=models.CharField(default='empty', max_length=30),
        ),
    ]
