# Generated by Django 3.2 on 2021-05-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduler', '0016_course_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
