# Generated by Django 3.2.2 on 2021-05-07 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduler', '0016_course_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='ta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Scheduler.user'),
        ),
    ]
