# Generated by Django 3.2 on 2021-05-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduler', '0017_alter_user_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='maxsection',
            field=models.IntegerField(default=0),
        ),
    ]
