# Generated by Django 3.2 on 2021-05-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduler', '0018_alter_user_maxsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='maxsection',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
