# Generated by Django 3.2 on 2021-05-08 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduler', '0017_section_ta'),
        ('Scheduler', '0019_alter_user_maxsection'),
    ]

    operations = [
    ]
