# Generated by Django 3.1.7 on 2021-05-08 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduler', '0019_alter_user_maxsection'),
        ('Scheduler', '0017_section_ta'),
    ]

    operations = [
    ]
