# Generated by Django 3.2 on 2021-05-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduler', '0020_merge_0017_section_ta_0019_alter_user_maxsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='remainingSection',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
